version: '3.7'
services:

  quasar-dev:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '9012:9012'
    volumes:
      - '.:/app'
    command: /bin/sh -c "npm i && quasar dev"

  quasar-prod:
    build:
      context: .
    ports:
      - '9013:80'
