version: '3.7'
services:

  tachideskvui-dev:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '9012:9012'
    volumes:
      - '.:/app'
    command: /bin/sh -c "npm i && quasar dev"
    restart: unless-stopped

  tachideskvui-prod:
    build:
      context: .
    ports:
      - '9013:80'
    restart: unless-stopped
