# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["Release"]
  pull_request:
    branches: ["Release"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: build for pages
        if: github.event_name != 'pull_request'
        run: PUBPATH=/Tachidesk-VUI/ npm run build
      - name: Deploy Pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/pwa # The folder the action should deploy.
      - run: npm run build
      - name: Generate Tag Name
        id: GenTagName
        run: |
          genTag="r$(git rev-list HEAD --count)"
          echo "$genTag"
          echo "value=$genTag" >> $GITHUB_OUTPUT
      - name: Generate zip
        uses: montudor/action-zip@v1
        if: github.event_name != 'pull_request'
        with:
          args: zip -qq -r release.zip dist/pwa
      - name: Upload CI Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          tag: ${{ steps.GenTagName.outputs.value }}
      # no idea if any of this will work so imma leave it for now
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.repository_owner }}/tachidesk-vui:latest
# i would also like to do pages, but idk where to even start with that
